export const FAKE_POPULARS = [
  {
    backdrop_path: "/hwIAR9FDsKULo8efoOUuxsFtO2u.jpg",
    first_air_date: "2008-01-20",
    genre_ids: [18, 80],
    id: 1396,
    name: "Breaking Bad",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    popularity: 377.672,
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    vote_average: 8.9,
    vote_count: 11455,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/hPea3Qy5Gd6z4kJLUruBbwAH8Rm.jpg",
    id: 60059,
    name: "Better Call Saul",
    original_language: "en",
    original_name: "Better Call Saul",
    overview:
      'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
    poster_path: "/iB6x0bA9XdP4MH3i1zXjMzvTNSY.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 128.937,
    first_air_date: "2015-02-08",
    vote_average: 8.619,
    vote_count: 3956,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 481.316,
    first_air_date: "2011-04-17",
    vote_average: 8.436,
    vote_count: 20931,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 270.3,
    first_air_date: "2016-07-15",
    vote_average: 8.635,
    vote_count: 15391,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/iprMfJ9VHS4wMhBXyHtN7l9d2hP.jpg",
    id: 1405,
    name: "Dexter",
    original_language: "en",
    original_name: "Dexter",
    overview:
      "Dexter Morgan, a blood spatter pattern analyst for the Miami Metro Police also leads a secret life as a serial killer, hunting down criminals who have slipped through the cracks of justice.",
    poster_path: "/58H6Ctze1nnpS0s9vPmAAzPcipR.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 103.531,
    first_air_date: "2006-10-01",
    vote_average: 8.2,
    vote_count: 3470,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    id: 1668,
    name: "Friends",
    original_language: "en",
    original_name: "Friends",
    overview:
      "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
    poster_path: "/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 246.211,
    first_air_date: "1994-09-22",
    vote_average: 8.452,
    vote_count: 6791,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/hmLTIRtVyTHShJl2Wb8LHmvUgJm.jpg",
    id: 19885,
    name: "Sherlock",
    original_language: "en",
    original_name: "Sherlock",
    overview:
      "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
    poster_path: "/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 64.082,
    first_air_date: "2010-07-25",
    vote_average: 8.533,
    vote_count: 4405,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
    id: 60625,
    name: "Rick and Morty",
    original_language: "en",
    original_name: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765, 10759],
    popularity: 499.085,
    first_air_date: "2013-12-02",
    vote_average: 8.723,
    vote_count: 8105,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/sMclUciz4ri4lmw7vdBZMdLIqry.jpg",
    id: 1402,
    name: "The Walking Dead",
    original_language: "en",
    original_name: "The Walking Dead",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    poster_path: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10765],
    popularity: 493.775,
    first_air_date: "2010-10-31",
    vote_average: 8.117,
    vote_count: 14834,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/lHe8iwM4Cdm6RSEiara4PN8ZcBd.jpg",
    id: 44217,
    name: "Vikings",
    original_language: "en",
    original_name: "Vikings",
    overview:
      "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
    poster_path: "/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10768],
    popularity: 365.866,
    first_air_date: "2013-03-03",
    vote_average: 8.079,
    vote_count: 6117,
    origin_country: ["CA"],
  },
  {
    adult: false,
    backdrop_path: "/r9t9lblyPfudl0LV0Ujg1nXdKyW.jpg",
    id: 1408,
    name: "House",
    original_language: "en",
    original_name: "House",
    overview:
      "Dr. Gregory House, a drug-addicted, unconventional, misanthropic medical genius, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital in New Jersey.",
    poster_path: "/5rIQ3pTjWdZjNUJSJxn1T8MIvoG.jpg",
    media_type: "tv",
    genre_ids: [18, 9648],
    popularity: 293.873,
    first_air_date: "2004-11-16",
    vote_average: 8.606,
    vote_count: 5424,
    origin_country: ["US"],
  },
];
